# == Classic ==
# This is a shorthand to override some of the options to be backwards compatible
# with `ls`. It affects the "color"->"when", "sorting"->"dir-grouping", "date"
# and "icons"->"when" options.
classic: false

# == Blocks ==
# Columns and their order when using the long and the tree layout.
blocks: # Possible values: permission, user, group, context, size, date, name, inode, links, git
  - permission
  - user
  - size
  - date
  - name

# == Color ==
color:
  when: auto  # Possible values: never, auto, always  
  theme: default  # Possible values: default, custom

# == Date ==
# This specifies the date format for the date column. The freeform format accepts a strftime like string.
# When "classic" is set, this is set to "date".
# Possible values: date, relative, '+<date_format>'
# `date_format` will be a `strftime` formatted value. e.g. `date: '+%d %b %y %X'` will give you a date like this: 17 Jun 21 20:14:55
date: '+%d %b %y %H:%M '

# == Dereference ==
dereference: false

# == Display ==
# What items to display. Do not specify this for the default behavior.
display: directory-only  # Possible values: all, almost-all, directory-only

# == Icons ==
icons:
  when: auto
  theme: fancy
  separator: "  "

# == Ignore Globs ==
# A list of globs to ignore when listing.
ignore-globs:
   - .git

# == Indicators ==
# Whether to add indicator characters to certain listed files.
# Possible values: false, true
indicators: false

# == Layout ==
# Which layout to use. "oneline" might be a bit confusing here and should be
layout: grid  # Possible values: grid, tree, oneline

# == Recursion ==
recursion:
  # Whether to enable recursion.
  enabled: false
  # How deep the recursion should go. This has to be a positive integer. Leave
  # it unspecified for (virtually) infinite.
  # depth: 3

# == Size ==
# Specifies the format of the size column.
size: default   # Possible values: default, short, bytes

# == Permission ==
permission: rwx # rwx, octal

# == Sorting ==
sorting:
  # Specify what to sort by.
  column: name    # Possible values: extension, name, time, size, version
  # Whether to reverse the sorting.
  reverse: false
  # Whether to group directories together and where.
  dir-grouping: none  # Possible values: first, last, none

# == No Symlink ==
# Whether to omit showing symlink targets
no-symlink: false

# == Total size ==
# Whether to display the total size of directories.
total-size: false

# == Hyperlink ==
# Attach hyperlink to filenames
hyperlink: never # Possible values: always, auto, never

# == Symlink arrow ==
# Specifies how the symlink arrow display, chars in both ascii and utf8
symlink-arrow: 

# == Header ==
header: false
