return {
  --   -- 'nvim-neo-tree/neo-tree.nvim',
  --   -- branch = 'v3.x',
  --   -- lazy = false,
  --   -- dependencies = {
  --   --   'nvim-lua/plenary.nvim',
  --   --   'nvim-tree/nvim-web-devicons',
  --   --   'MunifTanjim/nui.nvim',
  --   -- },
  --   -- opts = {
  --   --   close_if_last_window = true,
  --   --   enable_git_status = true,
  --   --   enable_diagnostics = true,
  --   --   filesystem = {
  --   --     filtered_items = {
  --   --       visible = true,
  --   --       hide_dotfiles = false,
  --   --       hide_gitignored = true,
  --   --     },
  --   --   },
  --   --   source_selector = {
  --   --     winbar = false,
  --   --     statusline = false,
  --   --   },
  --   --   window = {
  --   --     mappings = {
  --   --       ['<space>'] = 'none',
  --   --       ['l'] = 'open',
  --   --       ['h'] = 'close_node',
  --   --       ['<cr>'] = 'open',
  --   --       ['o'] = 'open',
  --   --       ['a'] = 'add',
  --   --       ['d'] = 'delete',
  --   --       ['r'] = 'rename',
  --   --       ['y'] = 'copy_to_clipboard',
  --   --       ['x'] = 'cut_to_clipboard',
  --   --       ['p'] = 'paste_from_clipboard',
  --   --       ['q'] = 'close_window',
  --   --       ['?'] = 'show_help',
  --   --     },
  --   --   },
  --   -- },
  --   -- keys = {
  --   --   {
  --   --     '<leader>ef',
  --   --     '<cmd>Neotree focus<cr>',
  --   --     desc = 'Focus Neo-tree (filesystem)',
  --   --   },
  --   --   {
  --   --     '<leader>eb',
  --   --     '<cmd>Neotree buffers toggle<cr>',
  --   --     desc = 'Buffers',
  --   --   },
  --   --   {
  --   --     '<leader>eg',
  --   --     '<cmd>Neotree git_status toggle<cr>',
  --   --     desc = 'Git status',
  --   --   },
  --   --   {
  --   --     '<leader>et',
  --   --     '<cmd>Neotree toggle<cr>',
  --   --     desc = 'Toggle Neo-tree',
  --   --   },
  --   -- },
  --   -- enabled = false,
  --   {
  --     'nvim-tree/nvim-tree.lua',
  --     version = '*',
  --     lazy = false,
  --     requires = {
  --       'nvim-tree/nvim-web-devicons',
  --     },
  --     config = function()
  --       require('nvim-tree').setup {}
  --     end,
  --     keys = {
  --       {
  --         '<leader>e',
  --         '<cmd>NvimTreeFindFileToggle<cr>',
  --         desc = 'NvimTree',
  --       },
  --     },
  --   },
  -- Visualize buffers as tabs
  -- {
  --   'akinsho/bufferline.nvim',
  --   version = '*',
  --   event = 'VeryLazy',
  --   dependencies = {
  --     'nvim-tree/nvim-web-devicons',
  --   },
  --   config = function()
  --     vim.opt.termguicolors = true
  --     vim.opt.showtabline = 2
  --
  --     require('bufferline').setup {}
  --
  --     vim.keymap.set('n', '<Tab>', '<Cmd>BufferLineCycleNext<CR>', { desc = 'Siguiente buffer' })
  --     vim.keymap.set('n', '<S-Tab>', '<Cmd>BufferLineCyclePrev<CR>', { desc = 'Buffer anterior' })
  --   end,
  -- },
}
