live_config_reload = true

import = [
  #"~/.config/alacritty/catppuccin-macchiato.toml",
  #"~/.config/alacritty/catppuccin-frappe.toml",
  "~/.config/alacritty/catppuccin-mocha.toml",

  # Keybindings
  "~/.config/alacritty/keybindings.toml"
]


[cursor]
blink_interval = 500
blink_timeout = 5
unfocused_hollow = false

[cursor.style]
blinking = "Off"
shape = "Block"

[font]
size = 15

[font.normal]
family = "JetBrains Mono Nerd Font"
style = "Bold"

[scrolling]
history = 6000


[window]
title = "Alacritty"
#opacity = 0.9
#blur = true

[mouse]
hide_when_typing = true

[window.dimensions]
columns = 160
lines = 80

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 6
y = 6

[env]
TERM="xterm-256color"
