-- ----------------------------------------------------- 
-- Animations
-- Setup for the default animations
-- ----------------------------------------------------- 

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.curve("linear", { type = "bezier", points = { { 0, 0 }, { 1, 1 } } })
hl.curve("easeOutCubic", { type = "bezier", points = { { 0.65, 0 }, { 0.35, 1 } } })
hl.curve("easeInOutCirc", { type = "bezier", points = { { 0.85, 0 }, { 0.15, 1 } } })
hl.curve("easeOutCirc", { type = "bezier", points = { { 0, 0.55 }, { 0.45, 1 } } })
hl.curve("easeOutExpo", { type = "bezier", points = { { 0.16, 1 }, { 0.3, 1 } } })
hl.curve("md3_standard", { type = "bezier", points = { { 0.2, 0 }, { 0, 1 } } })
hl.curve("md3_decel", { type = "bezier", points = { { 0.05, 0.7 }, { 0.1, 1 } } })
hl.curve("md3_accel", { type = "bezier", points = { { 0.3, 0 }, { 0.8, 0.15 } } })
hl.animation({
    leaf = "windows",
    enabled = true,
    speed = 2.5,
    bezier = "easeOutExpo",
    style = "popin",
})
hl.animation({
    leaf = "border",
    enabled = true,
    speed = 10,
    bezier = "default",
})
hl.animation({
    leaf = "fade",
    enabled = true,
    speed = 2.5,
    bezier = "md3_decel",
})
hl.animation({
    leaf = "workspaces",
    enabled = true,
    speed = 3.5,
    bezier = "easeOutExpo",
    style = "slide",
})
hl.animation({
    leaf = "specialWorkspace",
    enabled = true,
    speed = 3,
    bezier = "md3_decel",
    style = "slidevert",
})
hl.animation({
    leaf = "layersIn",
    enabled = true,
    speed = 2.5,
    bezier = "easeOutCubic",
    style = "popin",
})
hl.config({
    animations = {
        enabled = true,
    },
})

