-- ----------------------------------------------------- 
-- General window decoration
-- ----------------------------------------------------- 

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.config({
    decoration = {
        blur = {
            enabled = true,
            size = 2,
            passes = 4,
            new_optimizations = true,
            ignore_opacity = true,
            xray = true,
        },
        -- drop_shadow = true
        -- shadow_range = 10
        -- shadow_render_power = 2
        -- shadow_offset = 3 2
        -- col.shadow = rgba(0,0,0,0.6)
        -- col.shadow_inactive = rgba(0,0,0,0.5)
        rounding = 7,
        dim_inactive = true,
        dim_strength = 0.085,
        dim_special = 0,
    },
})

