-- Keyboard Layout
-- https://wiki.hyprland.org/Configuring/Variables/#input
-- -----------------------------------------------------
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.config({
	input = {
		kb_layout = "es",
		numlock_by_default = false,
		follow_mouse = 1,
		follow_mouse_threshold = 100,
		focus_on_close = 2,
		mouse_refocus = true,
		touchpad = {
			natural_scroll = true,
		},
		sensitivity = 0.85, -- -1.0 - 1.0, 0 means no modification.
		scroll_method = "2fg", --# 0: two-finger, 1: edge, 2: button
		kb_options = "caps:escape",
	},
})
