-- ----------------------------------------------------- 
-- General window layout and colors
-- ----------------------------------------------------- 

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.config({
    general = {
        gaps_in = 4,
        gaps_out = 7,
        border_size = 1,
        col = {
            active_border = "rgb(688FDA)",
        },
        layout = "dwindle",
        allow_tearing = true,
        resize_on_border = true,
        snap = {
            enabled = true,
            window_gap = 10,
            monitor_gap = 10,
        },
    },
})

